name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the feature you'd like.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Why would this be useful?
    validations:
      required: true
